Viewing Arrays and matricies

In [ ]:
import numpy as np

np.random.seed(42)
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4[:, :, :, :]

array([[[[6, 3, 7, 4, 6],
         [9, 2, 6, 7, 4],
         [3, 7, 7, 2, 5],
         [4, 1, 7, 5, 1]],

        [[4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6],
         [4, 8, 6, 1, 3]],

        [[8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7],
         [3, 1, 5, 5, 9]]],


       [[[3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7],
         [9, 8, 8, 0, 8]],

        [[6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6],
         [9, 8, 6, 8, 7]],

        [[1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0],
         [4, 9, 6, 6, 8]]]], dtype=int32)

In [35]:
a4[:, :, :, :1]


array([[[[6],
         [9],
         [3],
         [4]],

        [[4],
         [0],
         [8],
         [4]],

        [[8],
         [4],
         [2],
         [3]]],


       [[[3],
         [9],
         [7],
         [9]],

        [[6],
         [7],
         [2],
         [9]],

        [[1],
         [4],
         [0],
         [4]]]], dtype=int32)

In [36]:
np.random.seed(7)
random_array = np.random.random((5,3))
random_array

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])